\c notesgoprojectdb

CREATE TABLE IF NOT EXISTS notes (
    ID SERIAL PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
)